name: Update Gist

on:
  push:
    branches: master

  schedule:
    - cron: "0 */12 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 875527647f0385c44b32085b548c267f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
